package com.muniai.api;
import static com.github.tomakehurst.wiremock.client.WireMock.configureFor; import static com.github.tomakehurst.wiremock.client.WireMock.okJson; import static com.github.tomakehurst.wiremock.client.WireMock.serverError; import static com.github.tomakehurst.wiremock.client.WireMock.stubFor; import static org.hamcrest.Matchers.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.github.tomakehurst.wiremock.WireMockServer; import com.muniai.bootstrap.MuniAiApplication; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource; import org.springframework.test.web.servlet.MockMvc;
@SpringBootTest(classes=MuniAiApplication.class,properties={"muniai.chat.max-message-length=5","muniai.ollama.timeout=1s"}) @AutoConfigureMockMvc @ActiveProfiles("test")
class ApiIntegrationTest {
 static final WireMockServer OLLAMA=new WireMockServer(0);
 @BeforeAll static void start(){OLLAMA.start();configureFor("localhost",OLLAMA.port());}
 @AfterAll static void stop(){OLLAMA.stop();}
 @BeforeEach void reset(){OLLAMA.resetAll();}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("muniai.ollama.base-url",OLLAMA::baseUrl);r.add("muniai.ollama.model",()->"llama3.2:3b");}
 @Autowired MockMvc mvc;
 @Test void emptyMessageValidationIncludesGeneratedCorrelationId() throws Exception {mvc.perform(post("/api/v1/chat").contentType("application/json").content("{\"message\":\" \"}")) .andExpect(status().isBadRequest()).andExpect(header().string("X-Correlation-ID",not(blankString()))).andExpect(jsonPath("$.code").value("INVALID_REQUEST")).andExpect(jsonPath("$.correlationId",not(blankString())));}
 @Test void maximumLengthValidation() throws Exception {mvc.perform(post("/api/v1/chat").contentType("application/json").content("{\"message\":\"123456\"}")) .andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("MESSAGE_TOO_LONG"));}
 @Test void propagatesCorrelationIdOnSuccess() throws Exception {stubFor(com.github.tomakehurst.wiremock.client.WireMock.post("/api/chat").willReturn(okJson("{\"model\":\"llama3.2:3b\",\"message\":{\"content\":\"yes\"}}")));mvc.perform(post("/api/v1/chat").header("X-Correlation-ID","test-id").contentType("application/json").content("{\"message\":\"hello\"}")) .andExpect(status().isOk()).andExpect(header().string("X-Correlation-ID","test-id")).andExpect(jsonPath("$.correlationId").value("test-id")).andExpect(jsonPath("$.answer").value("yes")).andExpect(jsonPath("$.provider").value("ollama"));}
 @Test void systemHealthReportsProviderAndModel() throws Exception {stubFor(com.github.tomakehurst.wiremock.client.WireMock.get("/api/tags").willReturn(okJson("{\"models\":[{\"name\":\"llama3.2:3b\"}]}")));mvc.perform(get("/api/v1/system/health")).andExpect(status().isOk()).andExpect(jsonPath("$.applicationStatus").value("UP")).andExpect(jsonPath("$.ollamaStatus").value("UP")).andExpect(jsonPath("$.model").value("llama3.2:3b")).andExpect(jsonPath("$.timestamp").exists());}
 @Test void globalExceptionMapsProviderFailure() throws Exception {stubFor(com.github.tomakehurst.wiremock.client.WireMock.post("/api/chat").willReturn(serverError()));mvc.perform(post("/api/v1/chat").contentType("application/json").content("{\"message\":\"hello\"}")) .andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.code").value("AI_PROVIDER_UNAVAILABLE")).andExpect(jsonPath("$.details").isArray()).andExpect(jsonPath("$.path").value("/api/v1/chat"));}
}
